input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "application" => "%{application_name}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "boonya-iot-logs-%{+YYYY.MM.dd}"
  }
}
