# 修改内容：修改人：pengjunlin 时间：2026-08-04 19:00:00 -- start ----
input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "application" => "%{application_name}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "boonya-iot-logs-%{+YYYY.MM.dd}"
  }
}
# 修改内容：修改人：pengjunlin 时间：2026-08-04 19:00:00 -- end ----
