version: '3.8'
services:
  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
    networks:
      - iot-network

  tdengine:
    image: tdengine/tdengine:latest
    ports:
        - "6030:6030"
        - "6041:6041"
        - "6060:6060"    # 新增ui，用于 taosExplorer
    environment:
      - TAOS_FIRST_EP=localhost:6030
    networks:
      - iot-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - iot-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - iot-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - emqx
      - tdengine
      - redis
      - minio
    ports:
      - "18080:18080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure
    networks:
      - iot-network

volumes:
  minio-data:

networks:
  iot-network:
    driver: bridge
